myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LogoutView
from account.views import SelectDivisionView, SignUpView, IncumbentSignUpView, SuccessSignUpView, ActivateView, SignInView, UpdateMypageView, mypost
from board.views import MainPageView, lotte_outer, lotte_add, index, detail, create, update, delete, create_comment, comment_delete, scrap

# for Media file전달
from django.conf import settings
from django.conf.urls.static import static

app_name = "board"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', MainPageView.as_view(), name='mainpage'),
    path('select_division', SelectDivisionView.as_view(), name='select_division'),
    path('signup/', SignUpView.as_view(), name='signup'),
    path('incumbent_signup/', IncumbentSignUpView.as_view(),
         name='incumbent_signup'),
    path('success_signup/', SuccessSignUpView.as_view(), name='success_signup'),
    path('account/activate/<str:uidb64>/<str:token>',
         ActivateView.as_view(), name='activate'),
    path('signin/', SignInView.as_view(), name='signin'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('mypage/<int:pk>/update', UpdateMypageView.as_view(), name='update_mypage'),
    path('mypage/<int:pk>/mypost', mypost, name='mypost'),
    # path('mypage/<int:pk>/update/nickname_update', NicknameUpdate(), name='nickname_update'),

    path('lotte_outer/<int:pk>', lotte_outer, name='lotte_outer'),

    path('index/<int:pk>', index, name='index'),
    path('create/<int:pk>', create, name='create'),

    # <int:pk> 회사 번호
    path('detail/<int:pk>/<int:post_id>', detail, name="detail"),
    path('update/<int:pk>/<int:post_id>', update, name="update"),
    path('delete/<int:pk>/<int:post_id>', delete, name="delete"),
    path('create_comment/<int:pk>/<int:post_id>',
         create_comment, name="create_comment"),
    path('comment_delete/<int:pk>/<int:post_id>/<int:com_id>',
         comment_delete, name="comment_delete"),
    path('scrap/<int:post_id>', scrap, name="scrap"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myproject/post/urls.py
# from django.urls import path
# from post.views import index, create, detail, update, delete, create_comment, comment_delete
# # for Media file전달
# from django.conf import settings
# from django.conf.urls.static import static
# urlpatterns = [
#     path('post/', index, name="post"),
#     path('create/', create, name="create"),
#     path('detail/<int:post_id>', detail, name="detail"),
#     path('update/<int:post_id>', update, name="update"),
#     path('delete/<int:post_id>', delete, name="delete"),
#     path('create_comment/<int:post_id>', create_comment, name="create_comment"),
#     path('comment_delete/<int:post_id>/<int:com_id>',
#          comment_delete, name="comment_delete"),
# ] 
# + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myproject/board/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone

# 식품, 유통, 화학/건설/제조, 관광/금융/서비스


class Type(models.Model):
    name = models.CharField(max_length=30, null=True)

    def __str__(self):
        return self.name

# 각 계열에 해당하는 회사 목록


class Company(models.Model):
    company_type = models.ForeignKey(
        Type, on_delete=models.CASCADE, related_name='types', null=True)
    subject = models.CharField('회사명', max_length=30, null=True)

    def __str__(self):
        return self.subject


####### post/models.py 합치기 #######

class Post(models.Model):
    boards_number = models.ForeignKey(
        Company, on_delete=models.CASCADE, related_name='board', null=True)

    author = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True, related_name="author_user")

    title = models.CharField('제목', max_length=100)
    desc = models.TextField('내용')

    scrap = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name="scrap_user")
    create_at = models.DateTimeField('작성시간', default=timezone.now)
    image = models.ImageField(
        '사진', upload_to='images/', blank=True, null=True, name='image')

    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, null=True)
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True, related_name="comment_user")
    company_type = models.ForeignKey(
        Company, on_delete=models.CASCADE, null=True)
    desc = models.CharField('내용', max_length=500)
    create_at = models.DateTimeField('작성시간', default=timezone.now)

    def __str__(self):
        return self.desc

    post = models.ForeignKey(Post, on_delete=models.CASCADE, null=True)
    image = models.ImageField(upload_to='images/', blank=True, null=True)

myproject/board/forms.py
from django.forms import ModelForm

from .models import Post, Comment

from django import forms


class PostForms(ModelForm):
    class Meta:
        model = Post

        fields = ('boards_number', 'title', "desc", 'image')

        widget = {
            'title': forms.TextInput(attrs={'class': 'temp'}),
        }


class CommentForms(ModelForm):
    class Meta:
        model = Comment
        fields = ("desc",)

myproject/board/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import get_user_model
from django.views.generic import TemplateView
from .models import Type, Company, Post, Comment
from .forms import PostForms, CommentForms
from django.core.paginator import Paginator
from django.http import HttpResponse
import json
User = get_user_model()

# 메인페이지 뷰


class MainPageView(TemplateView):
    template_name = 'mainpage.html'

    # context 뿌리는 메소드
    def get_context_data(self, **kwargs):

        user = self.request.user
        outer = Type.objects.all()

        context = {'user': user, 'outer': outer}
        return context

# 큰 계열 4개


def lotte_outer(request, pk):

    context = dict()

    outer = Type.objects.get(pk=pk)  # 4계열
    all_post = Post.objects.all()  # 전체 글
    specific_company_type = Company.objects.get(pk=pk)

    # 각 계열 별 filtering
    food_company_post = Company.objects.filter(company_type=5)
    retail_company_post = Company.objects.filter(company_type=6)
    chem_company_post = Company.objects.filter(company_type=7)
    tour_company_post = Company.objects.filter(company_type=8)

    # 필요없는 듯
    # company_post = Post.objects.filter(boards_number=specific_company_type)
    # context['company_post'] = company_post

    context['outer'] = outer
    context['all_post'] = all_post

    context['food_company_post'] = food_company_post
    context['retail_company_post'] = retail_company_post
    context['chem_company_post'] = chem_company_post
    context['tour_company_post'] = tour_company_post

    context['specific_company_type'] = specific_company_type

    # paginator
    all_company_post = [food_company_post,
                        retail_company_post,
                        chem_company_post,
                        tour_company_post]
# food_company_post
    paginator = Paginator(food_company_post, 6)
    page = request.GET.get('page')
    food_company_post = paginator.get_page(page)
    context['food_company_post'] = food_company_post

# retail_company_post
    paginator = Paginator(retail_company_post, 6)
    page = request.GET.get('page')
    retail_company_post = paginator.get_page(page)
    context['retail_company_post'] = retail_company_post

# chem_company_post
    paginator = Paginator(chem_company_post, 6)
    page = request.GET.get('page')
    chem_company_post = paginator.get_page(page)
    context['chem_company_post'] = chem_company_post

# tour_company_post
    # paginator = Paginator(tour_company_post, 6)
    # page = request.GET.get('page')
    # tour_company_post = paginator.get_page(page)
    # context['tour_company_post'] = tour_company_post

    # detail page  url 다룰 때 필요한데, 지금은 작동 X

    return render(request, 'lotte_outer.html', context)

# 회사 목록 추가(추가 다하면 없어도 O)


def lotte_add(request, pk):
    company = get_object_or_404(Type, pk=pk)

    if request.method == 'POST':
        subject = request.POST['subject']

        topic = Company.objects.create(
            subject=subject,
            company_type=company
        )

        return redirect('lotte_outer', pk=company.pk)
    return render(request, 'lotte_add.html', {'company': company})

####### post/views.py 합치기 #######


def index(request, pk):

    all_post = Post.objects.all()
    specific_company_type = Company.objects.get(pk=pk)
    company_post = Post.objects.filter(boards_number=specific_company_type)

    context = dict()

    context['all_post'] = all_post
    context['specific_company_type'] = specific_company_type
    context['company_post'] = company_post

    # paginator
    # paginator = Paginator(food_company_post, 8)
    # page = request.GET.get('page')
    # posts = paginator.get_page(page)
    # context['posts'] = posts

    return render(request, 'index.html', context)


def create(request, pk):
    context = dict()

    company_chk = Company.objects.get(pk=pk)

    context['company_chk'] = company_chk

    if request.method == 'POST':
        # media 파일 올려주려면, request.FILES 추가해주어야한다.
        temp_form = PostForms(request.POST, request.FILES)
        # temp_form.photo = request.FILES['image']

        if temp_form.is_valid():
            clean_form = temp_form.save(commit=False)
            clean_form.author = User.objects.get(id=request.user.id)
            # 추후에 User.id 할당해야해
            clean_form.save()

            return redirect('index', pk)
        else:
            context['write_form'] = PostForms()
            return render(request, 'write.html', context)
    else:
        context['write_form'] = PostForms()
        return render(request, 'write.html', context)


def detail(request, pk, post_id):
    context = dict()

    detail_post = Post.objects.get(id=post_id)
    company_chk = Company.objects.get(pk=pk)

    specific_company_type = Company.objects.get(pk=pk)
    context['specific_company_type'] = specific_company_type

    context['detail_post'] = detail_post
    context['comment_form'] = CommentForms()
    context['comment_all'] = Comment.objects.filter(
        post=Post.objects.get(id=post_id))  # 얘가 listview역할
    context['company_chk'] = company_chk

    return render(request, 'detail.html', context)


def update(request, pk, post_id):
    context = dict()
    company_chk = Company.objects.get(pk=pk)

    context['company_chk'] = company_chk

    if request.method == "POST":
        temp_form = PostForms(request.POST, request.FILES,
                              instance=Post.objects.get(id=post_id))

        if temp_form.is_valid():
            temp_form.save()
            return redirect('index', pk)
        else:
            context["write_form"] = temp_form
            return render(request, 'write.html', context)
    else:
        context["write_form"] = PostForms(
            instance=Post.objects.get(id=post_id))
        return render(request, 'write.html', context)


def delete(request, pk, post_id):
    detail_post = Post.objects.get(id=post_id)
    detail_post.delete()

    # User 정보 받아올 수 있을때 사용
    # if detail_post.author == request.user:
    #     detail_post.delete()
    return redirect('index', pk)


def create_comment(request, pk, post_id):
    company_index = Company.objects.get(pk=pk)
    context = {'company_index': company_index}

    if request.method == "POST":
        temp_form = CommentForms(request.POST)
        if temp_form.is_valid():
            clean_form = temp_form.save(commit=False)

            clean_form.post = Post.objects.get(id=post_id)
            clean_form.author = User.objects.get(id=request.user.id)

            clean_form.save()
            temp_form.save()
        return redirect('detail', pk, post_id)


def comment_delete(request, pk, post_id, com_id):
    del_com = Comment.objects.get(id=com_id)
    del_com.delete()
    return redirect('detail', pk, post_id)


def scrap(request, post_id):
    context = dict()
    target_post = Post.objects.get(id=post_id)
    if target_post.scrap.filter(id=request.user.id):
        target_post.scrap.remove(request.user)
        print("유저가 있다가 제거되었습니다.")
        context["flag"] = "None"
    else:
        target_post.scrap.add(request.user)
        print("user가 없다가 추가되었습니다")
        context["flag"] = "Exist"

    print(target_post.scrap.all())
    context["len"] = len(target_post.scrap.all())

    return HttpResponse(json.dumps(context), content_type='application/json')

myproject/board/templates/detail.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>게시판 상세 보기</title>
    <link rel="stylesheet" href="{% static 'css/detail.css' %}">

</head>

<body>
    <div class="container">
        <div id="header">
            <a href="{% url 'mainpage' %}"> <img src="{% static 'img/logo.png' %}" class="logo"></a>

            <span class="my_page"><a href="{% url 'mainpage' %}">마이페이지</a></span>
        </div>

        <div id="layout">
            <div class="company-list">
                <div id="business-field">식품<div class="dot--medium"></div>
                </div>
                <div class="company-box">
                    <div class="company-name">롯데제과</div>
                </div>
                <div class="company-box">
                    <div class="company-name">롯데푸드</div>
                </div>
                <div class="company-box">
                    <div class="company-name">롯데칠성음료</div>
                </div>
                <div class="company-box">
                    <div class="company-name">롯데 푸드</div>
                </div>
                <div class="company-box">
                    <div class="company-name">롯데 네슬레</div>
                </div>
                <div class="company-box">
                    <div class="company-name">롯데 아사히주류</div>
                </div>
                <div class="company-box">
                    <div class="company-name">롯데 유통사업 본부</div>
                </div>
                <div class="company-box">
                    <div class="company-name">롯데 중앙 연구소</div>
                </div>
                <div class="company-box">
                    <div class="company-name">롯데 지알에스</div>
                </div>
            </div>

            <div class="post-and-comment-container">
                <div class="post-container">
                    <div class="post-info">

                        <div class="post-writer"> {{detail_post.author}}</div>
                        <div class="post-title"> {{detail_post.title}} </div>
                        <div class="post-info-wrap">
                            <div class="current-time"> {{detail_post.create_at}}</div>
                            <div class="view-number">조회수 0</div>
                            <div class="scrap-number">스크랩 : {{detail_post.scrap.all|length}}</div>
                            <div class="comment-number">댓글 : {{comment_all|length}}</div>

                        </div>
                    </div>
                    <div class="post-content">
                        {{detail_post.desc}}
                    </div>

                    <div class="image-wrap">
                        {% if detail_post.image%}
                        <div class="image">
                            <img src="{{detail_post.image.url}}" alt="">
                        </div>
                        {% endif %}
                    </div>
                    <div class="btn-wrap">
                        <div class="btn--left">
                            <button class="btn">

                                {% if user in detail_post.scrap.all %}
                                <span class="scrap">🧡</span>
                                <input type="hidden" value="{{detail_post.id}}">
                                {%else%}
                                <span class="scrap">🖤</span>
                                <input type="hidden" value="{{detail_post.id}}">

                                {%endif%}
                            </button>
                            <a href="{% url 'index' company_chk.pk %}">
                                <button class="btn">
                                    글 목록
                                </button>
                            </a>
                        </div>
                        <div class="btn--right">


                            <button class="btn">
                                <a href="{% url 'update' company_chk.pk detail_post.id %}">수정</a>
                            </button>
                            <button class="btn">
                                <a href="{% url 'delete' company_chk.pk detail_post.id %}">삭제</a>
                            </button>
                        </div>
                    </div>
                </div>


                <div class="comment-container">
                    {% for com in comment_all%}

                    <div class="comment-writer-username">{{com.author}}</div>
                    <div class="comment-wrap">
                        <div class="comment-content">{{com}}</div>
                        <div class="comment-control-wrap">
                            <!-- <div class="comment-control"> -->
                            <a class="comment_delete"
                                href="{% url 'comment_delete' company_chk.pk detail_post.id com.id %}">❌</a>
                            <!-- </div> -->
                        </div>
                    </div>
                    {%endfor%}


                    <div class="comment-writing-container">
                        <form class="comment_form" action="{% url 'create_comment' company_chk.pk detail_post.id %}"
                            method="post">

                            <!-- <div class="comment-writing"> -->
                            {% csrf_token %}
                            {{ comment_form.as_p }}

                            <!-- </div> -->
                            <input type="submit" class="btn" value='작성'>
                            <!-- <button class="btn"> 
                            </button> -->
                        </form>
                    </div>
                </div>
            </div>
        </div>

    </div>

</body>

<footer>
    <div id="footer-nav"></div>
    <div id="footer-info">
        <div class="footer-info-text">
            Copyright © DOOBOO All Rights reserved.
        </div>
    </div>
</footer>

<script type="text/javascript" src="{% static 'js/scrap.js' %}"></script>

</html>

myproject/board/templates/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>회사별 게시판</title>
    <link rel="stylesheet" href="{% static 'css/post-list.css' %}">

</head>


<body>
    {% comment %}
    {% if user.is_authenticated %}
    {{user.nickname}} 님

    <a href="{% url 'mypage' user.pk %}">마이페이지</a>
    <a href="{% url 'logout' %}">로그아웃</a>
    {%else%}
    <a href="{% url 'signin' %}">로그인</a>
    <a href="{% url 'select_division' %}">회원가입</a>
    {% endif %}

    <div class="cnt_post">{{company_post|length}}개의 게시글</div>
    <a class="write-btn" href="{% url 'create' company_type.pk %}"> 글쓰기 </a><br>


    {% endcomment %}


    <div class="container">
        <div id="header">
            <a href="{% url 'mainpage' %}">
                <img src="{% static 'img/logo.png' %}" class="logo">
            </a>
            <span class="my_page"><a href="{% url 'mypost' user.pk %}">마이페이지</a></span>
        </div>

        <div id="layout">
            <div class="company-list">
                <div id="business-field">{{specific_company_type}}<div class="dot--medium"></div>
                </div>


            </div>
            <div class="post-container">
                <!--이거 간격 같게 어케 하나요...??-->
                <div id="post-list__head">
                    <div id="post-writer__head" class="post-writer head">닉네임</div>
                    <div id="post-title__head" class="post-title head">제목</div>
                    <div id="post-date__head" class="post-date head">게시 날짜</div>
                    <div id="post-views__head" class="post-views head">조회수</div>
                    <div id="post-scrap__head" class="post-scrap head">스크랩</div>
                    <div id="post-comment__head" class="post-comment head">댓글</div>
                </div>

                <div id="post-list">
                    {% for one_post in company_post %}

                    <a href="{% url 'detail' specific_company_type.pk one_post.id %}">
                        <div class="post-box">
                            <div class="post" id="post1">
                                <div class="post-writer"> {{one_post.author}}
                                </div>
                                <div class="post-title"> {{one_post}}
                                </div>
                                <div class="post-date">{{one_post.create_at|date:"Y-m-d"}}</div>

                                <div class="post-views">10000</div>
                                <div class="post-scrap">30</div>
                                <div class="post-comment">5</div>
                            </div>
                        </div>
                    </a>
                    {%endfor%}
                </div>
                <a class="write-btn" href="{% url 'create' specific_company_type.pk %}">
                    <div class="btn-wrap">
                        <button class="btn-create">게시글 작성</button>
                    </div>
                </a>
            </div>
        </div>

    </div>

</body>

<footer>
    <div id="footer-nav"></div>
    <div id="footer-info">
        <div class="footer-info-text">
            Copyright © DOOBOO All Rights reserved.
        </div>
    </div>
</footer>

<script>


    const a = "{{company_type|length}}";
    // console.log(a)

    // array2 = "{{company_type}}"
    // for (i = 0; i < array2.length; i++) {
    //     console.log(array2[i])
    // }
    function change(i) {
        var button = document.getElementById(i);
        button.style.background = 'red';
    }


    // for (var i = 0; i < a; ++i) {
    //     button1 = document.getElementsByName(i);
    // }

    // var button1 = document.getElementById('company-' + i);

    // button1.addEventListener("click", function () {
    //     button1.style.backgroundColor = "red";
    // });


</script>

</html>

myproject/board/templates/lotte_add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form method="post">
        {% csrf_token %}
        <div class="form-group">
          <label for="id_subject">Subject</label>
          <input type="text" class="form-control" id="id_subject" name="subject">
        </div>
        <button type="submit" class="btn btn-success">Post</button>
      </form>
</body>
</html>

myproject/board/templates/lotte_inner.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form method="post">
        {% csrf_token %}
        <div class="form-group">
          <label for="id_subject">Subject</label>
          <input type="text" class="form-control" id="id_subject" name="subject">
        </div>
        <button type="submit" class="btn btn-success">Post</button>
      </form>
</body>
</html>

myproject/board/templates/mainpage.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>메인페이지</title>
    <link rel="stylesheet" href="{% static 'css/mainpage.css' %}">
</head>

<body>
    <div class="container">
        <div class="header">
            <a href="{% url 'mainpage' %}">

                <img src="/media/images/logo.png" class="logo">
            </a>
            <div class="user-interaction-wrap">

                {%if user.is_authenticated%}
                {{user.nickname}} 님 반갑습니다.
                <a href="{% url 'mypost' user.pk %}">마이페이지</a>
                <a href="{% url 'logout' %}">로그아웃</a>
                {%else%}
                <div class="login-in"><a href="{% url 'signin' %}">로그인</a></div>
                <div class="sign-in"><a href="{% url 'select_division' %}">회원 가입</a></div>
                {%endif%}

            </div>
        </div>

        <!-- 요기서 안에 글씨랑 로고 넣으려고 하면 계속 앞에 친구가 붕뜨면서 이쁘게 안나옴 -->
        <div class="content-box">

            {% for o in outer %}
            <a href="{% url 'lotte_outer' o.pk %}">
                <div class="select-box" id="select--food">
                    {% if forloop.counter == 1 %}
                    <div class="logo-box"><img src="{% static 'img/1.png' %}" alt="logo" class="business-logo"></div>
                    {% elif forloop.counter == 2 %}
                    <div class="logo-box"><img src="{% static 'img/2.png' %}" alt="logo" class="business-logo">
                    </div>
                    {% elif forloop.counter == 3 %}
                    <div class="logo-box"><img src="{% static 'img/3.png' %}" alt="logo" class="business-logo">
                    </div>
                    {% else %}
                    <div class="logo-box"><img src="{% static 'img/4.png' %}" alt="logo" class="business-logo">
                    </div>
                    {% endif %}
                    <div class="business-name">
                        {{o}}
                    </div>
                </div>
            </a>

            {% endfor %}
        </div>
    </div>
</body>
<footer>
    <div id="footer-nav"></div>
    <div id="footer-info">
        <div class="footer-info-text">
            Copyright © DOOBOO All Rights reserved.
        </div>
    </div>
</footer>

</html>

myproject/board/templates/write.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>새 글 작성</title>
    <link rel="stylesheet" href='{% static "css/write.css" %}' type="text/css" />
</head>

<body>
    <div class="container">

        <div class="nav_bar">
            <a href="{% url 'mainpage' %}">
                <img src="{% static 'img/logo.png' %}" class="logo">
            </a>
        </div>

        <div class="post-container">
            <form method="POST" action="{% url 'create' company_chk.pk %}" enctype="multipart/form-data">
                {% csrf_token %}
                {{company_chk}}
                {{write_form.title}}
                {{write_form.desc}}
                <!-- {{write_form.boards}} -->

                <input type="hidden" name="boards_number" value="{{company_chk.pk}}">

                <div class="btn-wrap">
                    <div class="btn--left">
                        <label for="id_image">파일</label>
                        {{write_form.image}}


                    </div>
                    <div class="btn--right">
                        <button class="btn">작성 완료</button>
                    </div>
            </form>

            </form>
        </div>
    </div>
</body>

</html>