myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LogoutView
from account.views import SelectDivisionView, SignUpView, IncumbentSignUpView, SuccessSignUpView, ActivateView, SignInView, UpdateMypageView, mypost
from board.views import MainPageView, lotte_outer, lotte_add, index, detail, create, update, delete, create_comment, comment_delete, scrap

# for Media file전달
from django.conf import settings
from django.conf.urls.static import static

app_name = "board"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', MainPageView.as_view(), name='mainpage'),
    path('select_division', SelectDivisionView.as_view(), name='select_division'),
    path('signup/', SignUpView.as_view(), name='signup'),
    path('incumbent_signup/', IncumbentSignUpView.as_view(),
         name='incumbent_signup'),
    path('success_signup/', SuccessSignUpView.as_view(), name='success_signup'),
    path('account/activate/<str:uidb64>/<str:token>',
         ActivateView.as_view(), name='activate'),
    path('signin/', SignInView.as_view(), name='signin'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('mypage/<int:pk>/update', UpdateMypageView.as_view(), name='update_mypage'),
    path('mypage/<int:pk>/mypost', mypost, name='mypost'),
    # path('mypage/<int:pk>/update/nickname_update', NicknameUpdate(), name='nickname_update'),

    path('lotte_outer/<int:pk>', lotte_outer, name='lotte_outer'),

    path('index/<int:pk>', index, name='index'),
    path('create/<int:pk>', create, name='create'),

    # <int:pk> 회사 번호
    path('detail/<int:pk>/<int:post_id>', detail, name="detail"),
    path('update/<int:pk>/<int:post_id>', update, name="update"),
    path('delete/<int:pk>/<int:post_id>', delete, name="delete"),
    path('create_comment/<int:pk>/<int:post_id>',
         create_comment, name="create_comment"),
    path('comment_delete/<int:pk>/<int:post_id>/<int:com_id>',
         comment_delete, name="comment_delete"),
    path('scrap/<int:post_id>', scrap, name="scrap"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myproject/post/urls.py
# from django.urls import path
# from post.views import index, create, detail, update, delete, create_comment, comment_delete
# # for Media file전달
# from django.conf import settings
# from django.conf.urls.static import static
# urlpatterns = [
#     path('post/', index, name="post"),
#     path('create/', create, name="create"),
#     path('detail/<int:post_id>', detail, name="detail"),
#     path('update/<int:post_id>', update, name="update"),
#     path('delete/<int:post_id>', delete, name="delete"),
#     path('create_comment/<int:post_id>', create_comment, name="create_comment"),
#     path('comment_delete/<int:post_id>/<int:com_id>',
#          comment_delete, name="comment_delete"),
# ] 
# + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myproject/account/models.py
from django.db import models
from django.contrib.auth.base_user import BaseUserManager
from django.contrib.auth.models import AbstractBaseUser
from django.contrib.auth.models import PermissionsMixin

# Create your models here.

# django 모델들은 Manager를 통해서 QuerySet을 받기 때문에, DB에서 query를 처리할 때 Manager를 거쳐야 함
# 따라서, User를 Custom할거니 UserManager도 함께 커스텀


class UserManager(BaseUserManager):  # BaseUserManager : User 생성 시 모델 관리 및 생성 시 기능 지정

    # user 생성 메소드 - 이메일, 패스워드, 닉네임 기본 ++ 사진, 계열은 superuser에서 필수 아니므로 초기화
    def _create_user(self, email, password, nickname, picture=None, division=1, **extra_fields):
        if not email:  # 이메일 필수
            raise ValueError('The given email must be set')

        user = self.model(
            email=self.normalize_email(email),  # 이메일 정규화
            nickname=nickname,
            picture=picture,
            division=division,
            **extra_fields
        )

        user.set_password(password)  # 비밀번호 설정
        user.save(using=self._db)  # 저장
        return user

    # user 중 일반user 생성 메소드
    def create_user(self, email, nickname, password, **extra_fields):
        extra_fields.setdefault('is_staff', False)  # 스태프 X
        extra_fields.setdefault('is_active', True)  # 등록 O
        extra_fields.setdefault('is_superuser', False)  # 슈퍼유저 X

        # user 생성
        return self._create_user(email, password, nickname, **extra_fields)

    # user 중 superuser 생성 메소드 - 이메일, 패스워드, 닉네임은 필수
    def create_superuser(self, email, password, nickname, **extra_fields):
        extra_fields.setdefault('is_staff', True)  # 스태프 O
        extra_fields.setdefault('is_active', True)  # 등록 O
        extra_fields.setdefault('is_superuser', True)  # 슈퍼유저 O

        # 에러 잡기
        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff = True')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser = True')
        if extra_fields.get('is_active') is not True:
            raise ValueError('Superuser must have is_active = True')

        # user 생성
        return self._create_user(email, password, nickname, **extra_fields)


# AbstractBaseUser : 이것을 상속받아 모델을 재구성 (AbstractUser는 기본 필드 모델을 새로 정의할 수 없기 때문에 사용 X)
# PermissionsMixin : 권한 관련(is_staff 등) 모여있는 클래스 - 상속받아 모델 재구성
class User(AbstractBaseUser, PermissionsMixin):
    # 취준생 or 현직자 구분 선택
    DIVISION_CHOICES = (
        (0, '취준생'),
        (1, '현직자'),
    )

    # 현직자일 경우 계열 선택
    LINE_CHOICES = (
        (0, '식품'),
        (1, '유통'),
        (2, '화학/건설/제조'),
        (3, '관광/서비스/금융')
    )

    # 필드 정의
    email = models.EmailField('이메일', unique=True)
    nickname = models.CharField('닉네임', max_length=20, unique=True)
    picture = models.ImageField(
        '프로필 사진', null=True, default="./images/userdefaultimg.png")
    division = models.IntegerField('가입 구분', choices=DIVISION_CHOICES)
    line = models.IntegerField(
        '계열', choices=LINE_CHOICES, null=True, blank=True)
    # is_staff는 넣어야 함 (is_superuser는 이미 있어서 O)
    is_staff = models.BooleanField('staff', default=False)
    # is_staff는 넣어야 함 (is_superuser는 이미 있어서 O)
    is_active = models.BooleanField('active', default=True)

    objects = UserManager()  # Manager 지정
    USERNAME_FIELD = 'email'  # username을 일반 ID 대신, email 그 자체로
    REQUIRED_FIELDS = ['nickname']  # 필수 필드(email, password는 기본 지정o)

    class Meta:
        verbose_name = '사용자'  # 단수
        verbose_name_plural = '사용자들'  # 복수

    def __str__(self):

        return self.email

myproject/account/forms.py
from django import forms
from .models import User
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.forms import AuthenticationForm
from django.contrib import auth
from django.contrib.auth import password_validation
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import update_session_auth_hash


# 일반 회원가입 폼
class SignUpForm(UserCreationForm): # 회원가입 기본 폼 상속 (패스워드, 패스워드확인)
    class Meta:
        model = User # 모델은 User 사용
        fields = ['email', 'password1', 'password2', 'nickname', 'picture'] # 필드 지정

    def clean(self, *args, **kwargs):
        email = self.cleaned_data.get('email')
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')
        nickname = self.cleaned_data.get('nickname')

        # 이메일 확인 - 이 부분 끌어서 중복확인 기능 만들 것
        try:
            User.objects.get(email=email)
            raise forms.ValidationError("이미 존재하는 이메일입니다.") # 존재하는 경우
        except User.DoesNotExist:
            pass
        if email is None: # email이 . 이 없는 경우 등 잘못 입력됐을 경우 None이 됨
            raise forms.ValidationError("올바른 이메일을 입력해주세요.")

        # 비밀번호 확인
        try:
            password_validation.validate_password(password1, self.instance)
        except forms.ValidationError:
            raise forms.ValidationError("8자 이하의 안전한 비밀번호로 설정해주세요.")
        if password1 != password2:
            raise forms.ValidationError("비밀번호가 일치하지 않습니다.")


        # 닉네임 확인 - 이 부분 끌어서 중복확인 기능 만들 것
        if len(nickname) >= 20:
            raise forms.ValidationError('닉네임이 20자 이상입니다. 20자 미만으로 입력하세요.')
        try:
            User.objects.get(nickname=nickname)
            raise forms.ValidationError("이미 존재하는 닉네임입니다.")
        except User.DoesNotExist:
            pass

        return self.cleaned_data

    # 저장 메소드
    def save(self, commit=True, *args, **kwargs):
        user = super(SignUpForm, self).save(commit=False) # 본인의 부모(UserCreationForm)를 호출하여 저장 + 일단 보류
        
        # 추가 필드 저장
        user.email = self.cleaned_data['email']
        user.nickname = self.cleaned_data['nickname']
        user.picture = self.cleaned_data['picture']
        user.division = 0
        user.is_active = False

        if commit:
            user.save() # User 생성
        return user




# 현직자 회원가입 폼
class IncumbentSignUpForm(SignUpForm): # 일반 회원가입 폼 상속        
    class Meta:
        model = User # 모델은 User 사용
        fields = ['email', 'password1', 'password2', 'nickname', 'picture', 'line'] # 필드 지정
    
    # 에러메시지 처리하기
    def clean(self, *args, **kwargs):
        super(IncumbentSignUpForm, self).clean(*args, **kwargs)

        email = self.cleaned_data.get('email')
        line = self.cleaned_data.get('line')

        if email.split('@')[1] != 'naver.com': # 이메일의 @ 뒷부분 (추후 변경)
            raise forms.ValidationError('롯데 이메일 계정이 아닙니다.') # forms.ValidationError 보내면, views의 form_invalid()에서 form.non_field_errors()로
        if line is None:
            raise forms.ValidationError('계열을 입력하세요.') # forms.ValidationError 보내면, views의 form_invalid()에서 form.non_field_errors()로


        return self.cleaned_data
    
    # 저장 메소드
    def save(self, commit=True, *args, **kwargs):
        user = super(IncumbentSignUpForm, self).save(commit=False, *args, **kwargs) # 본인의 부모(UserCreationForm)를 호출하여 저장 + 일단 보류
        
        # 추가 필드 저장
        user.division = 1
        user.line = self.cleaned_data['line']
        user.is_active = False

        if commit:
            user.save() # User 생성
        return user




# 로그인 폼
class SignInForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super(SignInForm, self).__init__(*args, **kwargs)        

        # 아이디 대신 이메일을 username으로
        UserModel = User



# 닉네임 수정 폼
class NicknameUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['nickname']


# 프로필사진 수정 폼
class PictureUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['picture']


# 비밀번호 수정 폼
class PasswordUpdateForm(PasswordChangeForm):
    # 필드
    old_password = forms.CharField(
        label='기존 비밀번호',
        strip=False,
        widget=forms.PasswordInput(attrs={'autocomplete': 'current-password', 'autofocus': True}),
    )
    new_password1 = forms.CharField(
        label='새 비밀번호',
        widget=forms.PasswordInput(attrs={'autocomplete': 'new-password'}),
        strip=False,
        help_text=password_validation.password_validators_help_text_html(),
    )
    new_password2 = forms.CharField(
        label='새 비밀번호 확인',
        strip=False,
        widget=forms.PasswordInput(attrs={'autocomplete': 'new-password'}),
    )

myproject/account/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.shortcuts import resolve_url, get_object_or_404
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic import TemplateView
from django.contrib.auth.views import LoginView
from django.contrib import messages
from django.core.mail import EmailMessage
from django.contrib import auth
from django.conf import settings
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode
from django.utils.http import urlsafe_base64_decode
from django.shortcuts import redirect
from django.http import JsonResponse
from django.core.exceptions import ValidationError
from .token import account_activation_token
from .text import message
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from .forms import SignUpForm, IncumbentSignUpForm, SignInForm, NicknameUpdateForm, PictureUpdateForm, PasswordUpdateForm
from .models import User
from board.models import Post

# Create your views here.

# 회원가입 구분 선택 뷰
class SelectDivisionView(TemplateView):
    template_name = 'registration/select_division.html'

# 회원가입 뷰
class SignUpView(CreateView): # 회원가입 기본 뷰 상속
    template_name = 'registration/signup.html'
    form_class = SignUpForm # 폼은 SignUpForm 사용
    user = None

    def get_success_url(self):
        # 인증이메일 보내기
        domain = "http://127.0.0.1:8000/" # 추후 변경
        uidb64 = urlsafe_base64_encode(force_bytes(self.user.pk))
        token = account_activation_token.make_token(self.user)
        message_data = message(domain, uidb64, token)

        email = EmailMessage(
            '이메일 인증을 완료해주세요.',
            message(domain, uidb64, token),
            to=[self.user.email]
        )
        email.send()

        return reverse_lazy('success_signup') # reverse_laze : 해당 url로 실행

    def form_valid(self, form):
        self.user = form.save() # 폼 저장할 때 return한 user 가져와서 저장해두기
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, form.non_field_errors(), extra_tags='danger')
        return super().form_invalid(form)



# 현직자 회원가입 뷰
class IncumbentSignUpView(SignUpView):
    template_name = 'registration/incumbent_signup.html'
    form_class = IncumbentSignUpForm # 폼은 IncumbentSignUpForm 사용



# 회원가입 입력 완료 뷰
class SuccessSignUpView(TemplateView):
    template_name = 'registration/success_signup.html'



# 이메일 인증 처리 뷰
class ActivateView(TemplateView):
    template_name = 'registration/activate.html'

    def get(self, request, uidb64, token):
        try:
            uid = force_text(urlsafe_base64_decode(uidb64))
            user = User.objects.get(pk=uid) # user pk가 동일한지 확인

            if account_activation_token.check_token(user, token): # 동일하면
                user.is_active = True # active로 변경
                user.save() # 저장
                auth.login(request, user) # 자동 로그인

                return super(ActivateView, self).get(request, uidb64, token)

            return JsonResponse({"message": "AUTH FAIL"}, status=400) # 다르면 에러
        
        except ValidationError:
            return JsonResponse({"message": "TYPE_ERROR"}, status=400)
        except KeyError:            
            return JsonResponse({"message": "INVALID_KEY"}, status=400)
    
    

# 로그인 뷰
class SignInView(LoginView):
    template_name = 'registration/signin.html'
    form_class = SignInForm # 폼은 SignInForm 사용
    authentication_form = SignInForm

    def get_success_url(self):
        return resolve_url(settings.LOGIN_REDIRECT_URL) # 로그인 후, LOGIN_REDIRECT_URL로 넘어가기 (mainpage)

    def form_invalid(self, form):
        messages.error(self.request, '로그인에 실패하였습니다. ID 또는 Password를 확인해 주세요.', extra_tags='danger')
        return super().form_invalid(form)



# 마이페이지 정보 수정
class UpdateMypageView(TemplateView):
    ### TemplateResponseMixin
    template_name = 'mypage/update_mypage.html'

    ### ContextMixin 
    def get_context_data(self, **kwargs):
        """ Adds extra content to our template """
        context = super(UpdateMypageView, self).get_context_data(**kwargs)

        context['nickname_form'] = NicknameUpdateForm(
            instance = self.request.user,
            prefix='nickname_form', 
            data = self.request.POST if 'nickname_form-submit' in self.request.POST else None,
            )

        context['picture_form'] = PictureUpdateForm(
            instance = self.request.user,
            prefix='picture_form', 
            data = self.request.POST if 'picture_form-submit' in self.request.POST else None,
            files = self.request.FILES if 'picture_form-submit' in self.request.POST else None
            )

        context['password_form'] = PasswordUpdateForm(
            user = self.request.user,
            prefix='password_form', 
            # Multiple 'submit' button paths should be handled in form's .save()/clean()
            data = self.request.POST if 'password_form-submit' in self.request.POST else None,
            )

        return context


    def post(self, request, *args, **kwargs):
        context = self.get_context_data(**kwargs)

        if context['nickname_form'].is_valid():
            context['nickname_form'].save()
            messages.success(request, '닉네임 변경o')
        elif context['picture_form'].is_valid():
            context['picture_form'].save()
            messages.success(request, '사진 변경o')
        elif context['password_form'].is_valid():
            context['password_form'].save()
            update_session_auth_hash(request, self.request.user)  # 암호화하여 업뎃
            messages.success(request, '비번 변경o')
        else:
            messages.error(request, '저장x, 다시 확인')

        return self.render_to_response(context)

# 마이페이지 내가쓴글 뷰
def mypost(request, pk):
    user = request.user
    mypost = Post.objects.filter(author=user)

    context = {'user':user, 'mypost':mypost, 'pk':pk}

    return render(request, 'mypage/mypost.html', context)

myproject/account/templates/mypage/mypage.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/mypage.css' %}">
</head>

<body>
    <div class="background">
        <div class="header">
            <a href="{% url 'mainpage' %}">
                <img src="/media/images/logo.png" class="logo">
            </a>
            <div class="logout-btn">
                {{user.nickname}} | 로그아웃
            </div>
        </div>

        <div class="board-wrap">
            <div class="comp-wrap">
                <div class="comp-title">
                    마이페이지
                </div>
                <div class="comp-list">
                    <!-- 요기는 나중에 데이터 넣으면 for 문으로 돌아가게 하면 될 듯 -->
                    <div class="comp-box">
                        <div class="comp-name" id="name2">
                            내가 쓴 글
                        </div>
                    </div>

                    <div class="comp-box">
                        <div class="comp-name" id="name3">
                            스크랩한 글
                        </div>
                    </div>

                    <!-- 요 부분 예쁘게 수정해야돼요 -->
                    <div class="comp-box">
                        <div class="comp-name" id="name3">
                            <a href="{% url 'update_mypage' user.pk %}">정보수정</a>
                        </div>
                    </div>
                </div>
            </div>

            <div class="post-wrap">
                <div class="post-title">
                    제목 | 게시 날짜 | 조회 | 스크랩 | 댓글
                </div>
                <div class="post-box-wrap">
                    <div class="post-box">
                        <div class="post" id="post1">
                            주모! 샷다내려잇! 나 오늘 집안가!
                            | 20.10.01 | 9 | 1 | 3
                        </div>
                    </div>
                    <div class="post-box">
                        <div class="post" id="post2">
                            벌써 10월 1일입니다... | 20.10.01 | 8 | 0 | 12
                        </div>
                    </div>
                    <div class="post-box">
                        <div class="post" id="post1">
                            추석 잘 보내세영 히히 | 20.10.01 | 6 | 0 | 30
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div id="footer">
        <div id="footer-nav">
            <div class="container"></div>
        </div>
        <div id="footer-info">
            <div class="footer-info-text">
                Copyright © DOOBOO All Rights reserved.
            </div>
        </div>
    </div>
</body>

</html>

myproject/account/templates/mypage/mypost.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>내가 쓴 글</title>
    <link rel="stylesheet" href="{% static 'css/마이페이지.css' %}">
    <link rel="stylesheet" href="{% static 'css/마이페이지-좌측메뉴.css' %}">
</head>

<body>
    <div class="container">
        <div id="header">
            <a href="{% url 'mainpage' %}">
                <img src="/media/images/logo.png" class="logo">
            </a>
            <span id="logout"><a href="{% url 'logout' %}">로그아웃</a></span>
        </div>


        <!-- 로그인한 사람의 마이페이지가 맞는 경우 -->
        {%if user.pk is pk %}

        <div id="layout">
            <div id="my-page">마이페이지<div class="dot--medium"></div>
            </div>
            <div class="menu-list">
                <div class="menu-box" id="current-menu">
                    <a href="{% url 'mypost' user.pk %}">
                        <div class="menu-name">내가 쓴 글</div>
                    </a>
                </div>
                <div class="menu-box">
                    <a href="">
                        <div class="menu-name">스크랩한 글</div>
                    </a>
                </div>
                <div class="menu-box">
                    <a href="{% url 'update_mypage' user.pk %}">
                        <div class="menu-name">정보 수정</div>
                    </a>
                </div>
                </a>
            </div>


            <div class="post-wrap">
                <!-- <div class="post-title">
                    제목 | 게시 날짜 | 조회 | 스크랩 | 댓글
                </div> -->
                <div class="post-container">
                    <div id="post-list__head">
                        <div id="post-writer__head" class="post-writer head">닉네임</div>
                        <div id="post-title__head" class="post-title head">제목</div>
                        <div id="post-date__head" class="post-date head">게시 날짜</div>
                        <div id="post-views__head" class="post-views head">조회수</div>
                        <div id="post-scrap__head" class="post-scrap head">스크랩</div>
                        <div id="post-comment__head" class="post-comment head">댓글</div>
                    </div>
                    <div id="post-list">

                        {% for one_post in mypost %}
                        <a href="{% url 'detail' one_post.boards_number.id one_post.id %}">
                            <div class="post-box">
                                <div class="post" id="post1">
                                    <div class="post-writer">{{one_post.id}}</div>
                                    <div class="post-title">{{one_post}}</div>
                                    <div class="post-date">{{one_post.create_at|date:"Y-m-d"}}</div>
                                    <div class="post-views">10000</div>
                                    <div class="post-scrap">30</div>
                                    <div class="post-comment">5</div>
                                </div>
                            </div>
                        </a>
                        {%endfor%}
                    </div>
                </div>

                <!-- 다른 사람 마이페이지일 경우 -->
                {% else %}

                에러에러

                {% endif %}
            </div>
        </div>
    </div>

</body>
<footer>
    <div id="footer-nav"></div>
    <div id="footer-info">
        <div class="footer-info-text">
            Copyright © DOOBOO All Rights reserved.
        </div>
    </div>
</footer>

</html>

myproject/account/templates/mypage/update_mypage.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/update_mypage.css' %}">
</head>

<body>
    <div class="background">
        <div class="header">
            <a href="{% url 'mainpage' %}">
                <img src="/media/images/logo.png" class="logo">
            </a>
            <a href="{% url 'logout' %}">
                <div class="logout-btn">
                    로그아웃
                </div>
            </a>
        </div>

        <!-- 로그인한 사람의 마이페이지가 맞는 경우 -->
        {%if user.pk is pk %}

        <div class="board-wrap">
            <div class="comp-wrap">
                <div class="comp-list">
                    <div class="comp-box">
                        <div class="comp-name" id="name2">
                            <a href="{% url 'mypost' user.pk %}">내가쓴 글</a>
                        </div>
                    </div>

                    <div class="comp-box">
                        <div class="comp-name" id="name3">
                            스크랩한 글
                        </div>
                    </div>

                    <!-- 요 부분 예쁘게 수정해야돼요 -->
                    <div class="comp-box">
                        <div class="comp-name" id="name3">
                            <a href="{% url 'update_mypage' user.pk %}">정보수정</a>
                        </div>
                    </div>
                </div>
            </div>

            <div class="post-wrap">
                <div class="post-box-wrap">
                    <div class="change-title">
                        정보 수정
                    </div>
                    <hr>

                    <!--  이 부분 예쁘게 같이 보여주기 -->
                    이메일 : {{user.email}}
                    <br/>
                    가입 구분 : {{user.get_division_display}}
                    <br/>
                    {%if user.division is 1%}
                    계열 : {{user.get_line_display}}
                    {%endif%}
                    <br/>


                    닉네임 : 
                    <!-- 닉넴 수정 부분 -->
                    <form id='' class="" action="{% url 'update_mypage' user.pk %}" enctype="multipart/form-data"
                        method="post">
                        {% csrf_token %}

                        <input type="text" name="nickname_form-nickname" maxlength="20" required
                            id="id_nickname_form-nickname" value="{{user.nickname}}">

                        <input type="submit" name="{{ nickname_form.prefix }}-submit" value="닉네임 수정" />
                    </form>

                    <br>
                    <br>

                    <!-- 사진 수정 부분 -->
                    프로필 사진 :  <img src="{{user.picture.url}}" width="250px" height="250px">
                    <form id='' class="" action="{% url 'update_mypage' user.pk %}" enctype="multipart/form-data"
                        method="post">
                        {% csrf_token %}
                        <input type="file" name="picture_form-picture" required id="id_picture_form-picture">

                        <input type="submit" name="{{ picture_form.prefix }}-submit" value="프로필사진 수정" />
                    </form>

                    <br>
                    <br>
                    비밀번호 : 

                    <!-- 비번 수정 부분 -->
                    <form id='' class="" action="{% url 'update_mypage' user.pk %}" enctype="multipart/form-data"
                        method="post">
                        {% csrf_token %}
                        <input type="pasword" name="password_form-old_password" autofocus="" required
                            id="id_password_form-old_password" placeholder="현재 비밀번호">
                        <input type="pasword" name="password_form-new_password1" autofocus="" required
                            id="id_password_form-new_password1" placeholder="바꿀 비밀번호">
                        <input type="password" name="password_form-new_password2" autofocus="" required
                            id="id_password_form-new_password2" placeholder="비밀번호 확인">

                        <input type="submit" name="{{ password_form.prefix }}-submit" value="비밀번호 수정" />
                    </form>


                    <!-- 에러창 뜰 부분 (지금은 메시지로 표시) -->
                    {% if messages %}
                    <ul class="messages">
                        {% for message in messages %}
                        <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
                        {% endfor %}
                    </ul>
                    {% endif %}

                </div>
            </div>
        </div>

        <!-- 다른 사람 마이페이지일 경우 -->
        {% else %}

        에러에러

        {% endif %}

    </div>

    <div id="footer">
        <div id="footer-nav">
            <div class="container"></div>
        </div>
        <div id="footer-info">
            <div class="footer-info-text">
                Copyright © DOOBOO All Rights reserved.
            </div>
        </div>
    </div>
</body>

</html>